version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=$PORT
    ports:
      - "3000:3001"
    volumes:
      - .:/usr/app
      - node_modules:/usr/app/node_modules
    networks:
      - app-network
    command: npm start

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
